blank_issues_enabled: false
contact_links:
  - name: gosling GitHub Discussions
    url: https://github.com/repo-makeover/gosling/discussions
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github.com/repo-makeover/gosling/security/policy
    about: Please report security vulnerabilities here.
